### ISSUE TITLE
Examples naming issue

### ISSUE THREAD

**Issue by agdl** [arduino-libraries/Ciao#1]
I think that

> ThinkSpeakTalkBackRecv.ino

and

> ThinkSpeakTalkBackSend.ino

Should be renamed to

> Thin**g**SpeakTalkBackRecv.ino

and

> Thin**g**SpeakTalkBackSend.ino

**Comment by sergiotomasello** [comment]
@agdl, @facchinm changed the name of the examples [in this commit](https://github.com/arduino-libraries/Ciao/commit/1989cacdaa25e46d0b2d837b132bab6cb3b5a2d6).
